### ISSUE TITLE
The download-boxes.sh script fails in CI on new forks

### ISSUE THREAD

**Issue by devantler** [techno-tim/k3s-ansible#105]
## Expected Behavior

I expect that the `test.yaml` pipeline can execute on forked repositories without error.

## Current Behavior

The `test.yaml` pipeline fails when calling the `download-boxes.sh` script.

## Steps to Reproduce

1. Fork the repository.
2. Run the pipelines

## Context (variables)

Operating system: MacOS

Hardware: M1

### Variables Used

None as it happens in CI.

### Hosts

None as it happens during CI.

### Repro

Check my fork for a failed action. There is not much info to gain from it, but it does prove that it fails on fresh forks: <https://github.com/devantler/k3s-ansible/actions>

## Possible Solution

I think it might be related to caching, in case you have not cached any vagrant boxes, and it tries to download them with the script. 

- [x] I've checked the [General Troubleshooting Guide](https://github.com/techno-tim/k3s-ansible/discussions/20)

**Comment by sleiner** [comment]
Great catch, @devantler! I pushed a fix (and an explanation of the error) at #106 :-)

**Comment by devantler** [comment]
Thanks, that explains it :-) Happy to help!
