### ISSUE TITLE
Suggestion: Remove metallb and use kube-vip for both control plane and for service loadbalancing

### ISSUE THREAD

**Issue by sharifm-informatica** [techno-tim/k3s-ansible#116]
Kube-vip now can do both jobs so no need for metallb. This will simplify the install. also it will avoid arp spam from two different layer2 loadbalancers on the same network.

For reference: [https://kube-vip.io/docs/about/features/](https://kube-vip.io/docs/about/features/)

**Comment by timothystewart6** [comment]
Thanks!  I am aware however due to MetalLB's popularity we are going to stick with it for now!
