### ISSUE TITLE
Modular and Iterative Installation

### ISSUE THREAD

**Issue by inadarei** [techno-tim/k3s-ansible#118]
The K3S-Ansible setup has a very monolithical approach in its current design, making it an all-or-nothing proposition. I think it would be more usable and less error-prone if it was designed to gradually and incrementally increase deployment complexity:

1. Install K3s cluster with a single master 
2. Install Etcd and support multiple masters
3. Add kube-vip and Metal-LB support

The benefits of such gradual setup and modularity are:
1. Users can choose to stop at 1, if they don't really need 2 and 3, or stop at 2, if they don't need 3
2. The setup run would be easier to debug, because you have smaller steps, and after each step you get something working. For instance, with current design if Metal-LB setup or config fails, I don't even get a working K3s cluster, because Metal-LB installation is way too early. That is adding unnecessary fragility, in my opinion.

Thank you

**Comment by timothystewart6** [comment]
Thanks for this.  While this does sound nice, it's not currently how it's designed or architected, nor I am sure we'll go that route.  Feel free to fork this if you want this feature!
