### ISSUE TITLE
Consider Self-Hosted Runners for Performance

### ISSUE THREAD

**Issue by timothystewart6** [techno-tim/k3s-ansible#149]
CI takes a while to run, which is to be expected since we are spinning up VirtualBox VMs on a macOS via GitHub.  I've tried running this in kubernetes #136  however Kubernetes isn't the right tool for the job considering that it uses containers and this CI pipeline needs to create and run VMs.

2 options if performance continues to be an issue:

**Self Host VMs**
* Create a dedicated VM for runners that will pick up the jobs.
* This is the easiest route and takes the least amount of change
* Will just need to configure a VM to handle this

**Use K8s but provision Proxmox as a VM provider for Vagrant**
* This would allow use to use Kubernetes to coordinate the work and scale up, but then use Proxmox host for the virtual machines that are used and tested.
* This would be the most challenging because we would have to swap the provider from VirtualBox to Proxmox and store secrets etc.
* Some of the work was already done in #136

**Comment by vdovhanych** [comment]
If you go the way of using self-hosted runners for GitHub actions that are triggered for pull-request, make sure [this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories) option is enabled. 
Also, ensure to only allow runs for pull requests that do not change workflow yaml configuration. This could lead to potentially unwanted code execution on the self-hosted runners and someone having access to a machine running in your environment.

**Comment by timothystewart6** [comment]
> If you go the way of using self-hosted runners for GitHub actions that are triggered for pull-request, make sure [this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories) option is enabled and set to `Require approval for all outside collaborators`. Also, ensure to only allow runs for pull requests that do not change workflow yaml configuration. This could lead to potentially unwanted code execution on the self-hosted runners and someone having access to a machine running in your environment.

Thank you!  For sure!  This is already enabled even prior to testing self-hosted runners!  I will also make sure to ignore yaml changes for workflows, good call!

**Comment by timothystewart6** [comment]
this was fixed by https://github.com/techno-tim/k3s-ansible/pull/389
