### ISSUE TITLE
netmask identification is not working with 10. addresses

### ISSUE THREAD

**Issue by Andre15711** [techno-tim/k3s-ansible#195]
The netmask identification is not working when the host is using 10. addresses like 10.10.10.10/24.
Script will fail, when trying to copy the vip.yaml template to the first node.

https://github.com/techno-tim/k3s-ansible/blob/e98e3ee77c7a07ed5ff1ab4588f394462c70b20f/roles/k3s/master/templates/vip.yaml.j2#L36

**Comment by timothystewart6** [comment]
duplicated of https://github.com/techno-tim/k3s-ansible/issues/196#issuecomment-1373829605
