### ISSUE TITLE
Provide galaxy.yml for this repo to work with ansible-galaxy

### ISSUE THREAD

**Issue by zeidoo** [techno-tim/k3s-ansible#198]
## Expected Behavior

Thank you for this repo and your videos! It's really helpful!

Would be nice if we could install this repo with ansible galaxy. The ansible docs state that there needs to be an galaxy.yml file in the repo. [1, 2]

Please note that I would do a PR, but, I'm not sure of what to put in it. I've attached a sample at the bottom of this issue though.

## Steps to Reproduce
User requirements.yml:

```
collections:
  - name: technotim.k3s
    source: https://github.com/techno-tim/k3s-ansible
    type: git
```

$ ansible-galaxy install -r ./collections/requirements.yml

ERROR! Neither the collection requirement entry key 'name', nor 'source' point to a concrete resolvable collection artifact. Also 'name' is not an FQCN. A valid collection name must be in the format <namespace>.<collection>. Please make sure that the namespace and the collection name contain characters from [a-zA-Z0-9_] only.

Tip: Make sure you are pointing to the right subdirectory — `some temp folder` looks like a directory but it is neither a collection, nor a namespace dir.

[1] https://docs.ansible.com/ansible/latest/galaxy/user_guide.html
[2] https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html)

## Sample galaxy.yml

```
namespace: "technotim"
name: "k3s"
version: "<todo>"
readme: "README.md"
authors:
    - "Techno Tim <insert your links here>"
dependencies:
    "other_namespace.collection1": ">=1.0.0"
    "other_namespace.collection2": ">=2.0.0,<3.0.0"
    "anderson55.my_collection": "*"    # note: "*" selects the highest version available
license:
    - "MIT"
tags:
    - demo
    - collection
repository: "https://github.com/techno-tim/k3s-ansible/"
```

**Comment by berendt** [comment]
That would really be an added value if you could install the roles via Galaxy independently of Github. This makes it much easier to use (at least for us with our workflows).
