### ISSUE TITLE
⚖️  Maintain Lineage vs. Keeping this repo clean

### ISSUE THREAD

**Issue by timothystewart6** [techno-tim/k3s-ansible#2]
I am having a hard time balancing maintaining lineage from a fork from a branch from a fork and making contributing easy.  While it is possible, it's really going to be challenging for PRs and other contributions.  I am considering dropping the lineage to the other repos, while still giving them credit in the `README.md`

**Comment by axlroden** [comment]
Hey, its just playbooks, and something people can get ideas from, although this is very tidy and well thought out.

**Comment by mxbranson** [comment]
I wouldn't worry about it. The originals and forks haven't been updated in ages. If some really spiffy feature gets added that your not ready to implement, you can always update the readme to note its existence, freeing you to update as you please.

Thanks for the mix. DIdn't know about the kubectl-vip and was using haproxy and a vip on my firewall to access a balanced cluster.

**Comment by timothystewart6** [comment]
Thank you,  I think I am going to clean up this repo to make it a little more approachable then and leave references to the old one in the `README.md`

**Comment by timothystewart6** [comment]
I've cleaned it up, added references and credits, and GitHub helped with the fork.  Going to close this
