### ISSUE TITLE
update playbooks to have boolean when needed true/false and not yes or no

### ISSUE THREAD

**Issue by jmbertoncelli** [techno-tim/k3s-ansible#204]
update playbooks to have boolean when needed true/false and not yes or no.

**Comment by timothystewart6** [comment]
Hey, thanks, It's definitely valid and ansible converts it to a boolean value.

**Comment by timothystewart6** [comment]
Just a note that if anyone takes this on, they will also need to update the linting rules too.

**Comment by irish1986** [comment]
I will have a crack at this and will need some help with comment and criticism.

**Comment by timothystewart6** [comment]
closed by https://github.com/techno-tim/k3s-ansible/issues/204
