### ISSUE TITLE
Ansible Version

### ISSUE THREAD

**Issue by smbonn2005** [techno-tim/k3s-ansible#242]
Should make a note when people install Ansible, to get via Pip and not apt, as at least the Ubuntu version is extremely behind and will cause issues with split.

**Comment by timothystewart6** [comment]
Thank you!  Minimum is `2.11`

**Comment by timothystewart6** [comment]
Done.  For context, `split` is not available until at least Ansible 2.11
https://github.com/techno-tim/k3s-ansible/commit/511c020bec98fa6c64f591fdf71c6ab10b0cfb2d
