### ISSUE TITLE
Ansible Task to Check Ansible Version

### ISSUE THREAD

**Issue by timothystewart6** [techno-tim/k3s-ansible#251]
We should have a task that checks to be sure that ansible meets the minimum version.  There have been lots of issues that have been reported about ansible not having `split` which is only available in later versions.

The current minimum is ` Ansible 2.11+`

https://github.com/techno-tim/k3s-ansible#-system-requirements

It might be as simple as this

https://www.jeffgeerling.com/blog/2018/require-minimum-ansible-version-your-playbook

Also, if the error message could link here that might be helpful, however not required https://docs.technotim.live/posts/ansible-automation/#installing-the-latest-version-of-ansible

**Comment by SaumyaBhushan** [comment]
I would like to work on this one .

**Comment by bdsoha** [comment]
This was implemented in #454, IMO this can be closed.

**Comment by timothystewart6** [comment]
closed by https://github.com/techno-tim/k3s-ansible/pull/454
