### ISSUE TITLE
Disable swap

### ISSUE THREAD

**Issue by dberardo-com** [techno-tim/k3s-ansible#266]
I assume that swap needs to be disabled during installation:

ref why: https://github.com/k3s-io/k3s-ansible/issues/147

ref how to: https://germaniumhq.com/2019/02/14/2019-02-14-Disabling-Swap-for-Kubernetes-in-an-Ansible-Playbook/

**Comment by egandro** [comment]
Don't mess with this in k3s-ansible.

I have a preflight.yml and do whatever it requires in there. e.g. swap, enable/disable ipv6, install nfs-common, LANG to C.UTF-8, install ntp and htpdate (for fixing the clock after a VM restore), install qemu-guest-agent,

So you see there is plenty to do - totaly legit - but it is 1000% out of the scope of k3s-ansible.

**Comment by egandro** [comment]
Preflight is my own file I created.... (preflight.yml).

**Comment by egandro** [comment]
Check this: https://pastebin.com/3XPzSQfT
