### ISSUE TITLE
Getting k3s.node.service and bind address error after running the playbook

### ISSUE THREAD

**Issue by GHMCr** [techno-tim/k3s-ansible#282]
After running the playbook for 3 nucs with ubuntu server on them, everything seems to install and setup fine. But in the last steps I'm getting the following error for all 3 nodes (that are both master and node):

```
fatal: [node001.calmus.one]: FAILED! => changed=false 
  msg: |-
    Unable to start service k3s-node: Job for k3s-node.service failed because the control process exited with error code.
    See "systemctl status k3s-node.service" and "journalctl -xeu k3s-node.service" for details.

```
When running the journalctl command on the nodes I find:

`Error starting load balancer: listen tcp 127.0.0.1:6444: bind: address already in use`

I don't know how to fix this.

**Comment by timothystewart6** [comment]
Hi @GHMCr  can you please fill out the template when opening an issue rather than deleting it?

**Comment by timothystewart6** [comment]
I am going to close this but feel free to open another issue and use the template
