### ISSUE TITLE
Move away from deprecated master role

### ISSUE THREAD

**Issue by twistedgrim** [techno-tim/k3s-ansible#339]
It would be nice to move to the newer control plane taints on nodes that are used as control plane nodes. As people use the playbook and charts and apps rely on the control plane taint more than a master taint it will start to cause issues. More info below.

Migrate from the old deprecated master taint to the new control-plane taint.
[Kubernetes docs ](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#urgent-upgrade-notes) from 1.20 show this change. 

- The label applied to control-plane nodes "node-role.kubernetes.io/master" is now deprecated and will be removed in a future release after a GA deprecation period.

- Introduce a new label "node-role.kubernetes.io/control-plane" that will be applied in parallel to "node-role.kubernetes.io/master" until the removal of the "node-role.kubernetes.io/master" label.

- Make "kubeadm upgrade apply" add the "node-role.kubernetes.io/control-plane" label on existing nodes that only have the "node-role.kubernetes.io/master" label during upgrade.

- Please adapt your tooling built on top of kubeadm to use the "node-role.kubernetes.io/control-plane" label.

- The taint applied to control-plane nodes "node-role.kubernetes.io/master:NoSchedule" is now deprecated and will be removed in a future release after a GA deprecation period.

- Apply toleration for a new, future taint "node-role.kubernetes.io/control-plane:NoSchedule" to the kubeadm CoreDNS / kube-dns managed manifests. Note that this taint is not yet applied to kubeadm control-plane nodes.

**Comment by egandro** [comment]
Same issue with hardcoded names "master" in the roles.

**Comment by bdsoha** [comment]
@twistedgrim 
CC: @egandro 
This seems to be fixed with the introduction of [`group_name_master`](https://github.com/techno-tim/k3s-ansible/blob/353f7ab6418ffe2ab46656579f32298c97379432/roles/k3s_server/defaults/main.yml).
IMO, this can be closed.

**Comment by timothystewart6** [comment]
closed by https://github.com/techno-tim/k3s-ansible/pull/337
