### ISSUE TITLE
main.yml issue. error - he error appears to be in '/home/xxxxx/k3s-ansible/roles/download/tasks/main.yml': line 3, column 3

### ISSUE THREAD

**Issue by network-slayer** [techno-tim/k3s-ansible#37]
The main.yml file doesn't seem to work anymore.

 FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: float object has no element 1\n\nThe error appears to be in '/home/xxxx/k3s-ansible/roles/download/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Download k3s binary x64\n  ^ here\n"}

Appears to be looking for an undefined variable

**Comment by timothystewart6** [comment]
can you post everything that was asked in the issue template?

**Comment by timothystewart6** [comment]
This should be working int he latest version, please pull and try again!
