### ISSUE TITLE
Fail Retry: Verify that all nodes actually joined 

### ISSUE THREAD

**Issue by sojjan1337** [techno-tim/k3s-ansible#395]
Hi!

Just doing some learning at home. Next step is to try out Loki and Mimir. But i can't get pass the following:

I keep getting this:

FAILED - RETRYING: [192.168.1.10]: Verify that all nodes actually joined (check k3s-init.service if this fails) (20 retries left).
FAILED - RETRYING: [192.168.1.82]: Verify that all nodes actually joined (check k3s-init.service if this fails) (19 retries left).
FAILED - RETRYING: [192.168.1.10]: Verify that all nodes actually joined (check k3s-init.service if this fails) (19 retries left).

Im running it on 4 laptops baremetal. Two master and two workers.
Masternode's are on 192.168.1.82 and 192.168.1.10
Worker nodes are on 192.168.1.11 and 192.168.1.12

Running rocky-linux 9.2

`fatal: [192.168.1.82]: FAILED! => {"attempts": 20, "changed": false, "cmd": ["k3s", "kubectl", "get", "nodes", "-l", "node-role.kubernetes.io/master=true", "-o=jsonpath={.items[*].metadata.name}"], "delta": "0:00:00.100517", "end": "2023-11-05 18:44:17.071077", "msg": "non-zero return code", "rc": 1, "start": "2023-11-05 18:44:16.970560", "stderr": "The connection to the server localhost:8080 was refused - did you specify the right host or port?", "stderr_lines": ["The connection to the server localhost:8080 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}
FAILED - RETRYING: [192.168.1.10]: Verify that all nodes actually joined (check k3s-init.service if this fails) (1 retries left).
fatal: [192.168.1.10]: FAILED! => {"attempts": 20, "changed": false, "cmd": ["k3s", "kubectl", "get", "nodes", "-l", "node-role.kubernetes.io/master=true", "-o=jsonpath={.items[*].metadata.name}"], "delta": "0:00:00.212869", "end": "2023-11-05 18:44:36.130774", "msg": "", "rc": 0, "start": "2023-11-05 18:44:35.917905", "stderr": "", "stderr_lines": [], "stdout": "master1", "stdout_lines": ["master1"]}`

flannel_iface: "eth0"
Not sure if this is a problem because the nic-name on the laptops are not the same. 
they are called like: enp0s25,enp2s0

apiserver_endpoint: "192.168.1.15"
metal_lb_ip_range: "192.168.1.20-192.168.1.30"

It works to ping the endpoint VIP "192.168.1.15"
I tried to set "setenforce 0" on all off them.

Thanks a bunch for helping out!

**Comment by sojjan1337** [comment]
worked on ubuntu server with same config.

**Comment by albal** [comment]
I have the same issue on Rocky 9.5
