### ISSUE TITLE
k3s-init.service fails

### ISSUE THREAD

**Issue by fabltd** [techno-tim/k3s-ansible#403]
Hi 

I have updated the version of K3s and Kube VIP in the vars all.yml.

I have 6 raspberry PIs ready to install.

Ansible always fails at the k3s-init.service. Whats the best way to debug why this fails?

**Comment by joaopedrocg27** [comment]
Also happened to me:

I ran  ``` k3s check-config ``` and saw that it was missing the necessary cgroups
<img width="841" alt="image" src="https://github.com/techno-tim/k3s-ansible/assets/30077840/22849c45-bb03-490b-b307-91dcee82e8e4">

Fixed it in #404

**Comment by fabltd** [comment]
Agreed: Fixed it in https://github.com/techno-tim/k3s-ansible/pull/404

**Comment by timothystewart6** [comment]
fixed by https://github.com/techno-tim/k3s-ansible/pull/404
