### ISSUE TITLE
Missing k3s_server_location: /var/lib/rancher/k3s/

### ISSUE THREAD

**Issue by Amoenus** [techno-tim/k3s-ansible#5]
Had to add `k3s_server_location: /var/lib/rancher/k3s/` to `inventory/my-cluster/group_vars/all.yml` for playbook to succeed

**Comment by timothystewart6** [comment]
Hey!  There was a bug that snuck in when I was cleaning up the repo.  If you pull latest it should be fixed!  Thanks for letting me know!

**Comment by timothystewart6** [comment]
I just tested with latest and it works

```
➜  repogit:(master) kubectl get nodes
NAME     STATUS   ROLES                       AGE   VERSION
k3s-01   Ready    control-plane,etcd,master   31h   v1.23.4+k3s1
k3s-02   Ready    control-plane,etcd,master   31h   v1.23.4+k3s1
k3s-03   Ready    control-plane,etcd,master   31h   v1.23.4+k3s1
k3s-04   Ready    <none>                      31h   v1.23.4+k3s1
k3s-05   Ready    <none>                      31h   v1.23.4+k3s1
```

Sorry about the bug, I fixed it shortly after but it was there for a few hours.  A `git pull` should fix it!

**Comment by waterfallm** [comment]
yeap i can confirm this fix works.. before the fix the kube-vip wasn't coming up.

**Comment by timothystewart6** [comment]
Thank you and sorry!

**Comment by Amoenus** [comment]
No need to apologize. Keep up the great work!!!
