### ISSUE TITLE
Test v1.29.2+k3s1 -> v1.29.4+k3s1 update

### ISSUE THREAD

**Issue by egandro** [techno-tim/k3s-ansible#506]
This is no bug!

I just open this ticket to get some confirmation from - who ever is testing this.

Some month ago, I added a patch to Tims nice scripts to allow updates.

Well - I did an update from **v1.29.2+k3s1** to **v1.29.4+k3s1** just by restarting the installer.

It works for me :)

Please confirm!

**Comment by egandro** [comment]
```bash
➜  homelab git:(main) ✗ kubectl version                                                                                                            
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4+k3s1
```

**Comment by timothystewart6** [comment]
@egandro  actually CI checks it, so it if works open a PR and CI automation will run and check it too!

**Comment by timothystewart6** [comment]
This was superseded by https://github.com/techno-tim/k3s-ansible/pull/532
