### ISSUE TITLE
Add minimum spec to README

### ISSUE THREAD

**Issue by 0lzi** [techno-tim/k3s-ansible#518]
Would be a good bit to put a minimum spec ( hardware wise ) in the README.

I Tried to follow along with the guide and installations kept failing.

I'm running this against VMs in proxmox, and although k3s shows recommended spec for control to be 2 CPU 1G RAM [link](https://docs.k3s.io/installation/requirements#hardware), these were not sufficient and it kept pinning the CPU of master node at 100% and the VIP kept disappearing from master but not going to another node. 

After some trail and error, I found that 4 CPU / 2G RAM is enough to get things going fine but not much wiggle room after putting rancher on there for deploying anything else.

Hardware: 3x Beelink SER5 ( Ryzen 5 5500U 6c/12t 16G RAM )

**Comment by timothystewart6** [comment]
Interesting! Typically min specs should be fine though etcd is sensitive to latency.  Could it have been that you were running other VMs on the shared disk at the time?

**Comment by 0lzi** [comment]
I had 1 other VM running on each node, but they are all on nvme local storage. I will do some more testing

**Comment by timothystewart6** [comment]
our specs should be no different than k3s specs https://docs.k3s.io/installation/requirements
