### ISSUE TITLE
Broken reference to metallb-webhook-service and invalid APT source for Ubuntu 24.04 LTS on arm64

### ISSUE THREAD

**Issue by winzlocom** [techno-tim/k3s-ansible#543]
I'd like to offer a fix/patch to the current master which accomplishess two things:
1.  Fixes an improper reference to metallb-webhook-service, which caused the deploy.sh to fail
2. Remove the kernel module involvement for Ubuntu 24.04 LTS on ARM64 (Raspberry PI) as it does not exist in the APT sources.

diff --git a/roles/k3s_server_post/tasks/metallb.yml b/roles/k3s_server_post/tasks/metallb.yml
index 07a23b0..363f4c3 100644
--- a/roles/k3s_server_post/tasks/metallb.yml
+++ b/roles/k3s_server_post/tasks/metallb.yml
@@ -85,7 +85,7 @@

 - name: Test metallb-system webhook-service endpoint
   command: >-
-    k3s kubectl -n metallb-system get endpoints webhook-service
+    k3s kubectl -n metallb-system get endpoints metallb-webhook-service
   changed_when: false
   with_items: "{{ groups[group_name_master | default('master')] }}"
   run_once: true
diff --git a/roles/raspberrypi/tasks/setup/Ubuntu.yml b/roles/raspberrypi/tasks/setup/Ubuntu.yml
index 72c77c9..93d55b9 100644
--- a/roles/raspberrypi/tasks/setup/Ubuntu.yml
+++ b/roles/raspberrypi/tasks/setup/Ubuntu.yml
@@ -7,7 +7,7 @@
     line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
   notify: reboot

-- name: Install linux-modules-extra-raspi
-  apt:
-    name: linux-modules-extra-raspi
-    state: present
+#- name: Install linux-modules-extra-raspi
+#  apt:
+#    name: linux-modules-extra-raspi
+#    state: present

**Comment by timothystewart6** [comment]
PR is welcome!

**Comment by timothystewart6** [comment]
We'll also need to be sure we can test this in CI with the Ubuntu 24.04 image.  That will need to be added to the PR as well.

**Comment by yebo29** [comment]
Can confirm that the fix for the metallb endpoint fixed the issue for me. My playbook runs were failing on that task. I can create a PR at some point today for that.

**Comment by yebo29** [comment]
Never mind. It seems [it was fixed already](https://github.com/techno-tim/k3s-ansible/commit/e8cd10d49bbde067471a3cd87d78165bdb5d765e#diff-83066302d9c94f3eb2eb2c611c377a77a29c397126aa466e87c2101317100f88)

**Comment by timothystewart6** [comment]
fixed by https://github.com/techno-tim/k3s-ansible/pull/576
