### ISSUE TITLE
apiserver_endpoint ip not assigned to all masters

### ISSUE THREAD

**Issue by juannicolas** [techno-tim/k3s-ansible#547]
## Current Behavior

Per the comment in project,  apiserver_endpoint ip should be virtually assigned to all master/ctrl servers (4) but is only been assigned to only 1

## Steps to Reproduce

1. Cloned repo and created local inventory folder with configurations (4 nodes master only)
2. Modify all.yml file and set apiserver_endpoint ip value
3. run ansible playbook site.yml
4. monitor process and check ip

## Context (variables)

set variable: apiserver_endpoint: "192.168.1.50"

Operating system:
Debian 12
Hardware:
2 proxmox cluster nodes

### Variables Used

`all.yml`
---
k3s_version: v1.29.2+k3s1
ansible_user: ansible
systemd_dir: /etc/systemd/system
system_timezone: "America/Puerto_Rico"
flannel_iface: "eth0"
calico_ebpf: false # use eBPF dataplane instead of iptables
calico_tag: "v3.27.2" # calico version tag
cilium_mode: "native" # native when nodes on same subnet or using bgp, else set routed
cilium_tag: "v1.15.2" # cilium version tag
cilium_hubble: true # enable hubble observability relay and ui
cluster_cidr: "10.52.0.0/16"
cilium_bgp: false
cilium_bgp_my_asn: "64513"
cilium_bgp_peer_asn: "64512"
cilium_bgp_peer_address: "192.168.30.1"
cilium_bgp_lb_cidr: "192.168.31.0/24" # cidr for cilium loadbalancer ipam
apiserver_endpoint: "192.168.1.50"
k3s_token: "Jxxxxxxxxxxxxx"
k3s_node_ip: "{{ ansible_facts[(cilium_iface | default(calico_iface | default(flannel_iface)))]['ipv4']['address'] }}"
k3s_master_taint: "{{ true if groups['node'] | default([]) | length >= 1 else false }}"
extra_args: >-
  {{ '--flannel-iface=' + flannel_iface if calico_iface is not defined and cilium_iface is not defined else '' }}
  --node-ip={{ k3s_node_ip }}
extra_server_args: >-
  {{ extra_args }}
  {{ '--node-taint node-role.kubernetes.io/master=true:NoSchedule' if k3s_master_taint else '' }}
  {% if calico_iface is defined or cilium_iface is defined %}
  --flannel-backend=none
  --disable-network-policy
  --cluster-cidr={{ cluster_cidr | default('10.52.0.0/16') }}
  {% endif %}
  --tls-san {{ apiserver_endpoint }}
  --disable servicelb
  --disable traefik

extra_agent_args: >-
  {{ extra_args }}

kube_vip_tag_version: "v0.7.2"
metal_lb_type: "native"
metal_lb_mode: "layer2"
metal_lb_speaker_tag_version: "v0.14.3"
metal_lb_controller_tag_version: "v0.14.3"
metal_lb_ip_range: "192.168.1.40-192.168.1.49"

proxmox_lxc_configure: false
proxmox_lxc_ssh_user: ansible
proxmox_lxc_ct_ids:
  - 100

custom_registries: false
custom_registries_yaml: |
  mirrors:
    docker.io:
      endpoint:
        - "https://registry.domain.com/v2/dockerhub"
    quay.io:
      endpoint:
        - "https://registry.domain.com/v2/quayio"
    ghcr.io:
      endpoint:
        - "https://registry.domain.com/v2/ghcrio"
    registry.domain.com:
      endpoint:
        - "https://registry.domain.com"

  configs:
    "registry.domain.com":
      auth:
        username: yourusername
        password: yourpassword

```ini

### Hosts

`host.ini`

```ini
[master]
192.168.1.[51:54] # control plain

[node]

[k3s_cluster:children]
master
node
```

## Possible Solution

- [x] I've checked the [General Troubleshooting Guide](https://github.com/techno-tim/k3s-ansible/discussions/20)

**Comment by timothystewart6** [comment]
How did you test?  what are you expectations?  I don't see any results.  This works in CI, we test a single node, so it seems to be related to your config.
