### ISSUE TITLE
Document Variables

### ISSUE THREAD

**Issue by timothystewart6** [techno-tim/k3s-ansible#560]
We should document variables and how to use them. Something as simple as an MD table in `README.md` would be nice but am open to other ideas.

| Variable | Default | Required | Description |
|---|---|---|---|
| k3s_version | none | yes | The version of k3s to use |
| ansible_user | none | yes | The ansible user that will be used |

etc...

**Comment by ednxzu** [comment]
Wild tangent here: but an mkdocs-material (or equivalent) static docs website for it ? coming from openstack, something like [this](https://docs.openstack.org/kolla-ansible/latest/reference/storage/external-ceph-guide.html) is really nice to read along when deploying.

using the wiki feature of github might also be an option, although I am not familiar with it, it could be a nice way to add bigger, more detailed documentation directly to the project ?

**Comment by timothystewart6** [comment]
Thanks!  I am open to it however I think first documenting it in the README is the path of least resistance.  It would also allow those making changes to update the corresponding documentation.

**Comment by Raytle** [comment]
It's not a wild tangent, but it is wishful thinking.

Solo FOSS devs are usually building something for fun and/or trying to solve a problem they care about. Writing detailed documentation isn’t something they usually enjoy, therefore they often don't give it much attention.

**Comment by 4t1l4** [comment]
Hi, I'm taking a stab at this as an attempt to get familiar with the project. Submitting a PR as soon as I can.
