### ISSUE TITLE
Unify use of k3s kubectl and kubectl and make it configurable

### ISSUE THREAD

**Issue by berendt** [techno-tim/k3s-ansible#566]
At the moment a mix of kubectl as well as k3s kubectl is used. I want to propose to use k3s kubectl everywhere by default and to make it configurable via a k3s_kubectl_binary parameter. This way it is possible to use kubectl instead of k3s kubectl (we have to use kubectl instead of k3s kubectl and have a manual patch at the moment to change it from k3s kubectl to kubectl where it is required for our use case).

**Comment by timothystewart6** [comment]
Sounds good to me!
