### ISSUE TITLE
Error Running playbook

### ISSUE THREAD

**Issue by glockdd** [techno-tim/k3s-ansible#568]
when i run the playbook i receive this error: 

ERROR! 'argument_specs' is not a valid attribute for a RoleMetadata

The error appears to be in '/home/francesco/kubernetes/k3s-ansible/roles/lxc/meta/main.yml': line 2, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
argument_specs:
^ here

Can you help me troubleshoot this?

**Comment by timothystewart6** [comment]
Hey, sorry, but you'll need to fill out the template.

**Comment by timothystewart6** [comment]
Hey, sorry, but you'll need to fill out the template.
