### ISSUE TITLE
Purpose of ansibleuser not obvious

### ISSUE THREAD

**Issue by technovangelist** [techno-tim/k3s-ansible#7]
In the all.yml file that defines all the variables to use, it wasn't immediately obvious to me what ansibleuser was for. At first I was thinking this was the user I am running ansible as. Which didn't make sense, so i commented it out. I have my controlplane and nodes set up in my ~/.ssh/config so the playbook was able to install stuff. But the kubeconfig file was getting copied to nowhere. That was my clue. So maybe clarify that `ansibleuser` is the user you are ssh'ing into the master and nodes. So on an ubuntu box, it may be ubuntu.

**Comment by timothystewart6** [comment]
Thanks, added a comment https://github.com/techno-tim/k3s-ansible/commit/24225c69c9f4b8fe75ab178774abc9d8a98c7330
