### ISSUE TITLE
Document Cluster Upgrade Steps

### ISSUE THREAD

**Issue by timothystewart6** [techno-tim/k3s-ansible#72]
This playbook also works for upgrading a cluster and all of its components.  

* Document steps in `README.md` on how to upgrade your cluster

**Comment by mingan666** [comment]
Any progress on this issue?
Would be interesting to know the best way of upgrading the repo, the versions or the cluster...

**Comment by timothystewart6** [comment]
You should be able to git pull latest and then rerun the repo, however the best way to upgrade kubernetes versions is by using https://github.com/rancher/system-upgrade-controller

**Comment by timothystewart6** [comment]
going to close this since this is really just a bootstrapper and upgrades should typically be handled by another tool / process.
