### ISSUE TITLE
YAML Linter

### ISSUE THREAD

**Issue by timothystewart6** [techno-tim/k3s-ansible#74]
Add YAML lint as a pre-commit hook to help commits fail fast, rather than in CI

**Comment by sleiner** [comment]
It could possibly be interesting to wrap our two linter steps into a single [`molecule lint`](https://molecule.readthedocs.io/en/latest/usage.html#lint) step (see [how to configure](https://molecule.readthedocs.io/en/latest/configuration.html#lint)). (Disclaimer: I have never used that feature until now).

**Comment by timothystewart6** [comment]
I have something almost working locally that will lint the files on pre-commit and share the rules with the linter curing CI

**Comment by vdovhanych** [comment]
I have been using for something like this a setup with committing `.git-hooks` folder to git. Create a make file that creates a symlink for pre-commit, and in that pre-commit is a script that calls `make lint` or whatever else you'd like and uses installed tools for linting. In this case, it would require `yamllint` to be present.

**Comment by timothystewart6** [comment]
Exactly!  I will try to open a PR tonight!

**Comment by timothystewart6** [comment]
Holding off for a bit until some PRs get closed, otherwise everyone will have to deal with conflicts with lint

**Comment by timothystewart6** [comment]
closed by https://github.com/techno-tim/k3s-ansible/pull/125
