### ISSUE TITLE
Support Single Node Installs

### ISSUE THREAD

**Issue by timothystewart6** [techno-tim/k3s-ansible#75]
We should support single node installs, installing all roles and all items on one node.  This gives someone the capability of running k3s one one node, with the flexibility of growing later.

**Comment by sleiner** [comment]
This is a setup I have been using with this playbook for a while. To make sure that this still works, I have opened #78. But [the tests are looking good over there also](https://github.com/techno-tim/k3s-ansible/runs/8265200948?check_suite_focus=true) - so what remains to be done here?

**Comment by timothystewart6** [comment]
https://github.com/techno-tim/k3s-ansible/pull/78 was merged.  I will test on my single machine soon.  I think they last time I tested it failed however now we have tests to prove it should work!

**Comment by timothystewart6** [comment]
@sleiner   CI flakiness now on single node?  https://github.com/techno-tim/k3s-ansible/runs/8274814832?check_suite_focus=true

**Comment by sleiner** [comment]
> CI flakiness now on single node? https://github.com/techno-tim/k3s-ansible/runs/8274814832?check_suite_focus=true


seems like it. Not sure how this came to be (I have no idea how the cert names are derived)... Let's see if that happens again?

**Comment by timothystewart6** [comment]
I did test and while it does technically work with a single node, it doesn't give that node the `worker` role.

Tested with

```ini
[master]
192.168.30.38

[k3s_cluster:children]
master
```

Wondering if there should either be a flag (to give all nodes all roles) or support adding the same IP to the hosts (isn't intuitive and could cause problems), or we just add the role at the end in a post step if there is only 1 IP in hosts.  

Open to ideas!

**Comment by sleiner** [comment]
> it doesn't give that node the `worker` role.

I have to admit that my knowledge is a bit shaky here. Would that be expected/necessary?

The tests show that you can deploy and use the example nginx workload just you would with a HA cluster.

**Comment by timothystewart6** [comment]
Good point.  I thought it was necessary.  I'll test some more.  I also need to learn more about the molecule overrides so I can use the same host settings

**Comment by timothystewart6** [comment]
I think this is working because we are not applying the taints

```
```

**Comment by timothystewart6** [comment]
closed by https://github.com/techno-tim/k3s-ansible/pull/93
