### ISSUE TITLE
Install was super quick

### ISSUE THREAD

**Issue by technovangelist** [techno-tim/k3s-ansible#8]
I used your cloudinit video to help create a better template on proxmox. But if you use that image as is, k3s runs out of space and stops without saying there is a problem. It wasn't until I ssh'd in and did a `k3s config-check` and saw there was a disk space issue. Increasing the size of disk wasn't a problem but it was a step I had to take that wasn't listed. At which point I found that your reset was really useful

**Comment by timothystewart6** [comment]
Thanks!  When using cloud init images you'll need to be sure you expand your disks depends on your use case for those vms.   Thank you!
